[Feature] 네트워크 통신 기능 및 DailyBoxOfficeListModel 타입 생성
Toydepromeet/assignment_style_toy pull request #2
Opened 2022-10-07 08:50 UTC by keeplo

## 구현 배경
#1 PR 에서 생성한 Model Entity 타입을 네트워크 통신으로 불러오는 동작 필요

## 기능 설명
### 구현코드
* `NetworkRequest: NetworkRequestable` - URLSession과 JSONDecode 작업 (일반화)
* `KoficAPI: API` - HTTPMethod에 맞춰 네트워크 요청

### 테스트 코드
* 프로토콜을 채택한 Mock 객체 형태로 네트워크 통신 테스트
* 시뮬레이션 테스트 - 아래 코드 작성하고 테스트 가능 (출력문생성됨)
   <img width="772" alt="스크린샷 2022-10-07 오후 5 17 47" src="https://user-images.githubusercontent.com/24707229/194512894-1df21978-a7bb-445c-b9f6-aa627184bde9.png">

2022-10-07 11:23 UTC, sustainable-git requested changes
combine을 정말 잘 쓰시는군요. 많이 배우겠습니다 :)

우리 indentation convention을 정해야 할 것 같아요!

2022-10-07 11:23 UTC, sustainable-git commented on ToyMovieList/ToyMovieList/Util/Network/API.swift
> +		let baseURL = URL(string: "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice")! // TODO: 변경예정
강제 언래핑 보다는 `init() throws` 로 error를 던지는게 어떨까요?

2022-10-07 11:23 UTC, sustainable-git commented on ToyMovieList/ToyMovieList/Util/Network/NetworkRequest.swift
> +struct NetworkRequest<Item: NetworkResponse>: NetworkRequestable {
제네릭을 정말 잘 쓰시는군요! 한 수 배웁니다.

2022-10-07 11:23 UTC, sustainable-git commented on ToyMovieList/ToyMovieList/Extension/Date+.swift
> +	func formattedTargetDt() -> String {
swift naming convention에는 약어를 지양하는 편이긴 한데, 우리만의 convention이 필요해 보이네요!

2022-10-07 11:23 UTC, sustainable-git commented on ToyMovieList/ToyMovieList/Util/Network/API.swift
> +		let lastDate = calendar.date(byAdding: .day, value: -1, to: Date()) ?? Date()
이건 어제 인가요?

2022-10-07 11:23 UTC, sustainable-git commented on ToyMovieList/ToyMovieListTests/Network/APITests.swift
> +	var sut: API!
sut는 어떤 의미인가요?

2022-10-07 14:08 UTC, keeplo commented on ToyMovieList/ToyMovieList/Util/Network/API.swift
> +		let baseURL = URL(string: "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice")! // TODO: 변경예정
강제 언래핑은 테스트 코드가 아닌 이상 저도 지양하는 편이라 동감합니다.

사실.. PR 전에 해야지 했던 부분인데.. 빠뜨렸네요 ㅠㅠ

`.plist` 나 다른 방법으로 URL을 따로 패키징 해야하지 않을까 생각하고 있습니다.
요 부분 수정 후 커밋 진행하고 다시 말씀드리겠습니다.

2022-10-07 14:10 UTC, keeplo commented on ToyMovieList/ToyMovieList/Extension/Date+.swift
> +	func formattedTargetDt() -> String {
아 좋습니다 Convention 필요할것 같아요..

고민하다가 JSON query 명칭 그대로 따라갔는데..
Swift.org 에서 공부할때 봐놓고... 놓쳤네요.. ㅠ
조금 더 네이밍 고민해보겠습니다.

2022-10-07 14:11 UTC, keeplo commented on ToyMovieList/ToyMovieList/Util/Network/API.swift
> +		let lastDate = calendar.date(byAdding: .day, value: -1, to: Date()) ?? Date()
넵 어제입니다!

음.. 좀 직관적이지 않은 것 같은데 Date extension 으로 빼보겠습니다 ㅎㅎ;;

2022-10-07 14:55 UTC, keeplo commented on ToyMovieList/ToyMovieList/Util/Network/API.swift
> +		let baseURL = URL(string: "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice")! // TODO: 변경예정
이전에 봤던 자료인데 참고했습니다 [애플리케이션의 민감한 정보를 보호하는 방법](https://nshipster.co.kr/secrets/)

`AppConfiguration` 같은 개체를 만들까 하다가 이번 PR에 설계와 스타일이 다른거 같아서..
말씀해주신 `init() throws` 방향으로 진행해봤습니다.

2022-10-08 07:52 UTC, sustainable-git approved these changes

2022-10-12 13:17 UTC, joseph704 commented on ToyMovieList/ToyMovieList/Util/Network/NetworkRequest.swift
> +	}
지난번 네트워크 로직 짜실 때, 반환 타입 (AnyPublisher<NetworkResponse, NetworkError>) 안맞아서 컴파일 에러 났던 걸 기가 막히게 해결 하셨군요 ㅎㅎ 한수 배우고 갑니다.

2022-10-12 13:19 UTC, joseph704 approved these changes
전체적으로 제너릭이랑 테스트코드 부분에서 많이 배워 갑니다!

2022-10-12 13:19 UTC, joseph704 commented on ToyMovieList/ToyMovieList/Util/Network/NetworkRequest.swift
> +	}
지난 번 네트워크 로직 짜실 때, 반환 타입(AnyPublisher<NetworkResponse, NetworkError>) 안맞아서 컴파일 에러 뜨던 부분을 기가 막히게 해결 하셨군요 ㅎㅎ 한수 배우고 갑니다!

2022-11-09 13:35 UTC, closed without merging